version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: composition
    volumes:
      - ./app:/CompositionBot/app
      - ./scripts/start.sh:/start.sh 
      - ./alembic:/CompositionBot/alembic
      - ./alembic.ini:/CompositionBot/alembic.ini
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=freelance.settings 
      - PYTHONUNBUFFERED=1
    command: 
     - sh 
     - -c
     - |
        chmod +x /start.sh && /start.sh
        
    depends_on: 
      - db
  db:
    image: postgres:14.6-alpine
    container_name: composition_db
    hostname: db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
  bot:
    build:
      context: .
    container_name: compostion_bot
    volumes:
      - ./bot:/CompositionBot/bot
      - ./scripts/start_bot.sh:/start.sh 
    command: 
      - sh 
      - -c
      - |
        chmod +x /start.sh && /start.sh
    env_file:
      - .env
  
volumes:
  db-data:
